[General]
network = Global
sim-time-limit = 10s

# для корректных расчётов
**.crcMode = "computed"
**.fcsMode = "computed"
**.checksumMode = "computed"

# -------------------------
# Адресация
# -------------------------
*.configurator.assignDisjunctSubnetAddresses = true
*.configurator.addStaticRoutes = true
*.configurator.addDefaultRoutes = true

**.internet.ipv4Delayer.config = xmldoc("internetCloud.xml")
*.extServer.numApps = 1

# Внешний сервер
**.extServer.app[0].typename = "TcpEchoApp"
**.extServer.app[0].localPort = 1000
**.extServer.app[0].echoDelay = 0s

**.branch*.office*.client[*].numApps = 1
**.branch*.localServer.numApps = 1
*.extServer.numApps = 1

# Внешний сервер
**.extServer.app[0].typename = "TcpEchoApp"
**.extServer.app[0].localPort = 1000
**.extServer.app[0].echoDelay = 0s

# Локальный сервер филиала
**.branch*.localServer.app[0].typename = "TcpEchoApp"
**.branch*.localServer.app[0].localPort = 1000
**.branch*.localServer.app[0].echoDelay = 0s

# Клиенты филиалов
**.branch*.office*.client[*].app[0].typename = "TcpSessionApp"
**.branch*.office*.client[*].app[0].active = true
**.branch*.office*.client[*].app[0].localPort = -1
**.branch*.office*.client[*].app[0].connectAddress = "extServer"
**.branch*.office*.client[*].app[0].connectPort = 1000
**.branch*.office*.client[*].app[0].tOpen = uniform(0.1s, 1s)
**.branch*.office*.client[*].app[0].tSend = 1s
**.branch*.office*.client[*].app[0].sendBytes = 1100B
**.branch*.office*.client[*].app[0].tClose = 9s